### ISSUE TITLE
import message crash at the end

### ISSUE THREAD

**Issue by ma2thieu** [tmo1/sms-ie#142]
Hello, I'm experiencing a crash when importing messages, it happens at the end of MMS importing.

In `messages-2023-12-05.zip` there is `messages.ndjson` and a folder `data` with all the images.
After the crash I can see all the messages in my SMS app but no image.

System : GrapheneOS
SMS App : QKSMS

During import I see a lot of lines like this : 
```
12-05 22:55:07.205  2790  3008 W System  : A resource failed to call AbstractCursor.close. 
```
And when it crashes at the end : 
```
12-05 22:55:08.307  9093  9093 E AndroidRuntime: FATAL EXCEPTION: main
12-05 22:55:08.307  9093  9093 E AndroidRuntime: Process: com.github.tmo1.sms_ie, PID: 9093
12-05 22:55:08.307  9093  9093 E AndroidRuntime: java.io.FileNotFoundException: No entry for content://mms/part/1248
12-05 22:55:08.307  9093  9093 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
12-05 22:55:08.307  9093  9093 E AndroidRuntime: 	at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:737)
12-05 22:55:08.307  9093  9093 E AndroidRuntime: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1897)
12-05 22:55:08.307  9093  9093 E AndroidRuntime: 	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1595)
12-05 22:55:08.307  9093  9093 E AndroidRuntime: 	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1569)
12-05 22:55:08.307  9093  9093 E AndroidRuntime: 	at b2.w.h(SourceFile:2)
12-05 22:55:08.307  9093  9093 E AndroidRuntime: 	at h3.a.b(SourceFile:1)
12-05 22:55:08.307  9093  9093 E AndroidRuntime: 	at u3.a0.run(SourceFile:1)
12-05 22:55:08.307  9093  9093 E AndroidRuntime: 	at kotlinx.coroutines.internal.d.run(Unknown Source:11)
12-05 22:55:08.307  9093  9093 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.i.run(Unknown Source:2)
12-05 22:55:08.307  9093  9093 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.a.run(SourceFile:77)
12-05 22:55:08.307  9093  9093 E AndroidRuntime: 	Suppressed: u3.y: [c1{Cancelling}@6b30e06, Dispatchers.Main]
```
Let me know if you need more log.
Thanks!

**Comment by tmo1** [comment]
> After the crash I can see all the messages in my SMS app but no image.

Are you saying that no images are imported?

We need to narrow down the problem - let's try to get a [minimal reproducible example](https://github.com/tmo1/sms-ie#bugs-feature-requests-and-other-issues). Try to do an export of only one MMS message - does importing such an export still crash? Does it matter which MMS message is in the file (you can try exporting a couple of messages and removing one by hand)?

**Comment by Hwmpunk** [comment]
I have the same issue. I can export 99k SMS messages and it only takes up 4mb, does that sound right?

But when I try to export 17k mms messages it goes through the whole count, then closes.

So I tried exporting 200 mms and got app closed unexpectedly message. Then tried 150 and it worked.

**Comment by tmo1** [comment]
> I can export 99k SMS messages and it only takes up 4mb, does that sound right?

Yes - SMS messages, including all their metadata, do not take up that much space, and being text, they compress quite well (via the ZIP compression).

> But when I try to export 17k mms messages it goes through the whole count, then closes.

The OP reported a problem with importing - is your problem with importing or exporting?

> So I tried exporting 200 mms and got app closed unexpectedly message. Then tried 150 and it worked.

As per [my message above](https://github.com/tmo1/sms-ie/issues/142#issuecomment-1842039288), please post a full logcat from a debug build using a minimal reproducible example message file.

**Comment by ma2thieu** [comment]
Hello, sorry for the late reply, here is the logcat from the last debug build : https://github.com/tmo1/sms-ie/actions/runs/7167672843

```
12-18 13:07:43.229   769  2075 D hwc-display: setActiveConfigWithConstraints:: PrimaryDisplay config(36) test(0)
12-18 13:07:43.229   769  2075 I hwc-display: [PrimaryDisplay] setActiveConfigWithConstraints: config(36)
12-18 13:07:43.328   769  2075 D hwc-display: setActiveConfigWithConstraints:: PrimaryDisplay config(37) test(0)
12-18 13:07:43.328   769  2075 I hwc-display: [PrimaryDisplay] setActiveConfigWithConstraints: config(37)
12-18 13:07:43.375  1239  1283 I RFSD    : [RfsService::Nv] ProcessMessage : RFS_IO_REQUEST
12-18 13:07:43.402  2326  2345 I deeptouch: I0000 00:00:1702901263.402588    2345 tf_lite_classifier.cc:409] Event stream classified as kNone
12-18 13:07:43.421  2149  2221 V WindowManagerShell: Transition requested: android.os.BinderProxy@17568d6 TransitionRequestInfo { type = 2, triggerTask = null, remoteTransition = null, displayChange = null, flags = 0 }
12-18 13:07:43.434   892   896 I libperfmgr: Hint type not present in actions: ADPF_DISABLE_TA_BOOST
12-18 13:07:43.437  1440  1440 D CompatibilityChangeReporter: Compat change id reported: 78294732; UID 10151; state: ENABLED
12-18 13:07:43.442   759   759 I BpBinder: onLastStrongRef automatically unlinking death recipients: 
12-18 13:07:43.643   767   767 W gralloc4: Unable to set buffer name VRI[MainActivity]#1(BLAST Consumer)1: File name too long
12-18 13:07:43.644   767   767 W gralloc4: Unable to set buffer name VRI[MainActivity]#1(BLAST Consumer)1: File name too long
12-18 13:07:43.644   767   767 W gralloc4: Unable to set buffer name VRI[MainActivity]#1(BLAST Consumer)1: File name too long
12-18 13:07:43.645   767   767 W gralloc4: Unable to set buffer name VRI[MainActivity]#1(BLAST Consumer)1: File name too long
12-18 13:07:43.646   767   767 W gralloc4: Unable to set buffer name VRI[MainActivity]#1(BLAST Consumer)1: File name too long
12-18 13:07:43.653  1438  1659 V WindowManager: Sent Transition #665 createdAt=12-18 13:07:43.420 via request=TransitionRequestInfo { type = 2, triggerTask = null, remoteTransition = null, displayChange = null, flags = 0 }
12-18 13:07:43.654  1438  1659 V WindowManager:     startWCT=WindowContainerTransaction { changes = {} hops = [] errorCallbackToken=null taskFragmentOrganizer=null }
12-18 13:07:43.654  1438  1659 V WindowManager:     info={id=665 t=CLOSE f=0x0 trk=0 r=[0@Point(0, 0)] c=[{null m=CLOSE f=FILLS_TASK leash=Surface(name=ActivityRecord{8576e47 u0 com.android.documentsui/.picker.PickActivity)/@0xa727737 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0},{null m=TO_FRONT f=FILLS_TASK leash=Surface(name=ActivityRecord{13772c6 u0 com.github.tmo1.sms_ie/.MainActivity)/@0x7cf2c36 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0}]}
12-18 13:07:43.654  2149  2221 V WindowManagerShell: onTransitionReady android.os.BinderProxy@17568d6: {id=665 t=CLOSE f=0x0 trk=0 r=[0@Point(0, 0)] c=[{null m=CLOSE f=FILLS_TASK leash=Surface(name=ActivityRecord{8576e47 u0 com.android.documentsui/.picker.PickActivity)/@0x730757 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0},{null m=TO_FRONT f=FILLS_TASK leash=Surface(name=ActivityRecord{13772c6 u0 com.github.tmo1.sms_ie/.MainActivity)/@0x180d244 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0}]}
12-18 13:07:43.654  2149  2221 V WindowManagerShell: Playing animation for (#665)android.os.BinderProxy@17568d6@0
12-18 13:07:43.654  2149  2221 V WindowManagerShell:  try handler com.android.wm.shell.transition.DefaultMixedHandler@d0b480f
12-18 13:07:43.655  2149  2221 V WindowManagerShell:  try handler com.android.wm.shell.keyguard.KeyguardTransitionHandler@85c709c
12-18 13:07:43.655  2149  2221 V WindowManagerShell:  try handler com.android.wm.shell.pip.PipTransition@e53aaa5
12-18 13:07:43.655  2149  2221 V WindowManagerShell:  try handler com.android.wm.shell.activityembedding.ActivityEmbeddingController@83c1e7a
12-18 13:07:43.655  2149  2221 V WindowManagerShell:  try handler com.android.wm.shell.recents.RecentsTransitionHandler@f3e562b
12-18 13:07:43.655  2149  2221 V ShellRecents: RecentsTransitionHandler.startAnimation: no controller found
12-18 13:07:43.655  2149  2221 V WindowManagerShell:  try handler com.android.wm.shell.splitscreen.StageCoordinator@c0dfa88
12-18 13:07:43.655  2149  2221 V WindowManagerShell:  try handler com.android.wm.shell.transition.RemoteTransitionHandler@1794c21
12-18 13:07:43.655  2149  2221 V WindowManagerShell: Transition doesn't have explicit remote, search filters for match for {id=665 t=CLOSE f=0x0 trk=0 r=[0@Point(0, 0)] c=[{null m=CLOSE f=FILLS_TASK leash=Surface(name=ActivityRecord{8576e47 u0 com.android.documentsui/.picker.PickActivity)/@0x730757 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0},{null m=TO_FRONT f=FILLS_TASK leash=Surface(name=ActivityRecord{13772c6 u0 com.github.tmo1.sms_ie/.MainActivity)/@0x180d244 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0}]}
12-18 13:07:43.655  2149  2221 V WindowManagerShell:  Checking filter Pair{{types=[] flags=0x0] notFlags=0x100 checks=[{atype=home independent=true modes=[OPEN,TO_FRONT] flags=NONE mustBeTask=false order=TOP topActivity=ComponentInfo{com.android.launcher3/com.android.launcher3.uioverrides.QuickstepLauncher}},{atype=standard independent=true modes=[CLOSE,TO_BACK] flags=NONE mustBeTask=false order=ANY topActivity=null}]} RemoteTransition { remoteTransition = android.window.IRemoteTransition$Stub$Proxy@3da1e91, appThread = android.app.IApplicationThread$Stub$Proxy@e5561f6, debugName = QuickstepLaunchHome }}
12-18 13:07:43.655  2149  2221 V WindowManagerShell:  Delegate animation for #665 to null
12-18 13:07:43.655  2149  2221 V WindowManagerShell:  try handler com.android.wm.shell.transition.DefaultTransitionHandler@85da846
12-18 13:07:43.655  2149  2221 V WindowManagerShell: start default transition animation, info = {id=665 t=CLOSE f=0x0 trk=0 r=[0@Point(0, 0)] c=[{null m=CLOSE f=FILLS_TASK leash=Surface(name=ActivityRecord{8576e47 u0 com.android.documentsui/.picker.PickActivity)/@0x730757 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0},{null m=TO_FRONT f=FILLS_TASK leash=Surface(name=ActivityRecord{13772c6 u0 com.github.tmo1.sms_ie/.MainActivity)/@0x180d244 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0}]}
12-18 13:07:43.655  2149  2221 V WindowManagerShell: loadAnimation: anim=android.view.animation.AnimationSet@cb6c1f3 animAttr=0x6 type=CLOSE isEntrance=true
12-18 13:07:43.656  2149  2221 V WindowManagerShell: loadAnimation: anim=android.view.animation.AnimationSet@e50bcae animAttr=0x7 type=CLOSE isEntrance=false
12-18 13:07:43.674   767   767 W gralloc4: Unable to set buffer name bbq-adapter#639(BLAST Consumer)639: File name too long
12-18 13:07:43.675  2565  2898 V MmsProvider: accessRestricted=false
12-18 13:07:43.684  2565  2898 V MmsProvider: accessRestricted=false
12-18 13:07:43.689  1438  1487 I ImeTracker: com.github.tmo1.sms_ie:91c1312f: onRequestHide at ORIGIN_SERVER_HIDE_INPUT reason HIDE_UNSPECIFIED_WINDOW
12-18 13:07:43.689  1438  1487 I ImeTracker: com.github.tmo1.sms_ie:91c1312f: onCancelled at PHASE_SERVER_SHOULD_HIDE
12-18 13:07:43.706   767   767 W gralloc4: Unable to set buffer name bbq-adapter#640(BLAST Consumer)640: File name too long
12-18 13:07:43.710  2149  2221 V WindowManagerShell:  animated by com.android.wm.shell.transition.DefaultTransitionHandler@85da846
12-18 13:07:43.712  3879  4041 D MediaProvider: Open with FUSE. FilePath: /storage/emulated/0/Share/messages-2023-12-09.zip. Uid: 10040. Media Capabilities Uid: 0. ShouldRedact: false. ShouldTranscode: false
12-18 13:07:43.763  1440  1546 D SMSIE   : Processing line #0
12-18 13:07:43.764  1440  1546 D SMSIE   : Message is SMS
12-18 13:07:43.785  1438 30262 D ActivityManager: sync unfroze 30663 android.process.acore for 7
12-18 13:07:43.807  2565  3140 V MmsProvider: accessRestricted=false
12-18 13:07:43.808  1440  1546 D SMSIE   : SMS insert succeeded
12-18 13:07:43.810  1440  1546 D SMSIE   : Processing line #1
12-18 13:07:43.812  1440  1546 D SMSIE   : Message is MMS
12-18 13:07:43.829  1440  1546 D SMSIE   : MMS insert succeeded
12-18 13:07:43.832  1440  1546 D SMSIE   : MMS address insert succeeded
12-18 13:07:43.834  1440  1546 D SMSIE   : MMS address insert succeeded
12-18 13:07:43.835  2565  2898 V MmsProvider: accessRestricted=false
12-18 13:07:43.836  1440  1546 D SMSIE   : MMS address insert succeeded
12-18 13:07:43.838  1440  1546 D SMSIE   : MMS address insert succeeded
12-18 13:07:43.841  1440  1546 D SMSIE   : MMS address insert succeeded
12-18 13:07:43.844  1440  1546 D SMSIE   : MMS address insert succeeded
12-18 13:07:43.847  1440  1546 D SMSIE   : MMS part insert succeeded
12-18 13:07:43.854  1440  1546 D SMSIE   : MMS part insert succeeded
12-18 13:07:43.865  3879  4041 D MediaProvider: Open with FUSE. FilePath: /storage/emulated/0/Share/messages-2023-12-09.zip. Uid: 10040. Media Capabilities Uid: 0. ShouldRedact: false. ShouldTranscode: false
12-18 13:07:43.869  1440  1546 D SMSIE   : Writing part: data/PART_1701708600109_7233852881.jpg
12-18 13:07:43.874  2565  3140 V MmsProvider: accessRestricted=false
12-18 13:07:43.895  1440  1440 E AndroidRuntime: FATAL EXCEPTION: main
12-18 13:07:43.895  1440  1440 E AndroidRuntime: Process: com.github.tmo1.sms_ie, PID: 1440
12-18 13:07:43.895  1440  1440 E AndroidRuntime: java.io.FileNotFoundException: No entry for content://mms/part/2526
12-18 13:07:43.895  1440  1440 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
12-18 13:07:43.895  1440  1440 E AndroidRuntime: 	at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:737)
12-18 13:07:43.895  1440  1440 E AndroidRuntime: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1897)
12-18 13:07:43.895  1440  1440 E AndroidRuntime: 	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1595)
12-18 13:07:43.895  1440  1440 E AndroidRuntime: 	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1569)
12-18 13:07:43.895  1440  1440 E AndroidRuntime: 	at com.github.tmo1.sms_ie.ImportExportMessagesKt$importMessages$2.invokeSuspend(ImportExportMessages.kt:648)
12-18 13:07:43.895  1440  1440 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-18 13:07:43.895  1440  1440 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
12-18 13:07:43.895  1440  1440 E AndroidRuntime: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
12-18 13:07:43.895  1440  1440 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
12-18 13:07:43.895  1440  1440 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
12-18 13:07:43.895  1440  1440 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
12-18 13:07:43.895  1440  1440 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
12-18 13:07:43.895  1440  1440 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
12-18 13:07:43.895  1440  1440 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b4ad07b, Dispatchers.Main]
12-18 13:07:43.900  1438  1551 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
12-18 13:07:43.900  1438  1487 W ActivityTaskManager:   Force finishing activity com.github.tmo1.sms_ie/.MainActivity
12-18 13:07:43.901  2149  2221 V WindowManagerShell: Transition requested: android.os.BinderProxy@e4dc3c8 TransitionRequestInfo { type = 2, triggerTask = null, remoteTransition = null, displayChange = null, flags = 16 }
12-18 13:07:43.914  1440  1440 I Process : Sending signal. PID: 1440 SIG: 9
12-18 13:07:43.944  2149  2221 V WindowManagerShell: Transition animation finished (aborted=false), notifying core (#665)android.os.BinderProxy@17568d6@0
12-18 13:07:43.944  1438 30262 I WindowManager: WIN DEATH: Window{489ae14 u0 com.github.tmo1.sms_ie/com.github.tmo1.sms_ie.MainActivity}
12-18 13:07:43.945  1438  2281 I ImeTracker: com.github.tmo1.sms_ie:86939692: onRequestHide at ORIGIN_SERVER_HIDE_INPUT reason HIDE_REMOVE_CLIENT
12-18 13:07:43.945  1438  5124 I ActivityManager: Process com.github.tmo1.sms_ie (pid 1440) has died: fg  TOP 
12-18 13:07:43.945  1438 30262 W InputManager-JNI: Input channel object '489ae14 com.github.tmo1.sms_ie/com.github.tmo1.sms_ie.MainActivity (client)' was disposed without first being removed with the input manager!
12-18 13:07:43.945  1015  1015 I Zygote  : Process 1440 exited due to signal 9 (Killed)
12-18 13:07:43.945   892   892 W libprocessgroup: Failed to apply NoResetUclampGrp task profile
12-18 13:07:43.946   892   892 W powerhal-libperfmgr: Failed to set NoResetUclampGrp task profile for tid:1494
12-18 13:07:43.946   892   892 W libprocessgroup: Failed to apply NoResetUclampGrp task profile
12-18 13:07:43.946  1438  2281 I ImeTracker: com.github.tmo1.sms_ie:86939692: onCancelled at PHASE_SERVER_SHOULD_HIDE
12-18 13:07:43.946   892   892 W powerhal-libperfmgr: Failed to set NoResetUclampGrp task profile for tid:1497
12-18 13:07:43.946   892   892 W libprocessgroup: Failed to apply NoResetUclampGrp task profile
12-18 13:07:43.946   892   892 W powerhal-libperfmgr: Failed to set NoResetUclampGrp task profile for tid:1440
12-18 13:07:43.946   892   892 W libprocessgroup: Failed to apply NoResetUclampGrp task profile
12-18 13:07:43.946   892   892 W powerhal-libperfmgr: Failed to set NoResetUclampGrp task profile for tid:1462
12-18 13:07:43.946  1438  1683 I libprocessgroup: Successfully killed process cgroup uid 10151 pid 1440 in 0ms
12-18 13:07:43.947  1438  1659 V WindowManager: Finish Transition #665: created at 12-18 13:07:43.420 collect-started=0.096ms request-sent=0.202ms started=8.64ms ready=13.146ms sent=232.384ms finished=527.152ms
12-18 13:07:43.949  2149  2221 V WindowManagerShell: Track 0 became idle
12-18 13:07:43.950  1438  1660 D DisplayManagerService: Drop pending events for gone uid 10151
12-18 13:07:43.955  2654  2654 D StatsLog: LAUNCHER_ONRESUME
12-18 13:07:43.955  2149  2221 D WindowManagerShell: setLauncherKeepClearAreaHeight: visible=true, height=294
12-18 13:07:43.963  1438  5124 W WindowManager: Failed to deliver inset control state change to w=Window{489ae14 u0 com.github.tmo1.sms_ie/com.github.tmo1.sms_ie.MainActivity EXITING}
12-18 13:07:43.963  1438  5124 W WindowManager: android.os.DeadObjectException
12-18 13:07:43.963  1438  5124 W WindowManager: 	at android.os.BinderProxy.transactNative(Native Method)
12-18 13:07:43.963  1438  5124 W WindowManager: 	at android.os.BinderProxy.transact(BinderProxy.java:584)
12-18 13:07:43.963  1438  5124 W WindowManager: 	at android.view.IWindow$Stub$Proxy.insetsControlChanged(IWindow.java:479)
12-18 13:07:43.963  1438  5124 W WindowManager: 	at com.android.server.wm.WindowState.notifyInsetsControlChanged(WindowState.java:3818)
12-18 13:07:43.963  1438  5124 W WindowManager: 	at com.android.server.wm.InsetsStateController.lambda$notifyPendingInsetsControlChanged$3(InsetsStateController.java:369)
12-18 13:07:43.963  1438  5124 W WindowManager: 	at com.android.server.wm.InsetsStateController.$r8$lambda$8yykPRG1GyNq_J17QvL9d5xANMc(InsetsStateController.java:0)
12-18 13:07:43.963  1438  5124 W WindowManager: 	at com.android.server.wm.InsetsStateController$$ExternalSyntheticLambda2.run(R8$$SyntheticClass:0)
12-18 13:07:43.963  1438  5124 W WindowManager: 	at com.android.server.wm.WindowAnimator.executeAfterPrepareSurfacesRunnables(WindowAnimator.java:294)
12-18 13:07:43.963  1438  5124 W WindowManager: 	at com.android.server.wm.RootWindowContainer.performSurfacePlacementNoTrace(RootWindowContainer.java:811)
12-18 13:07:43.963  1438  5124 W WindowManager: 	at com.android.server.wm.RootWindowContainer.performSurfacePlacement(RootWindowContainer.java:756)
12-18 13:07:43.963  1438  5124 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop(WindowSurfacePlacer.java:177)
12-18 13:07:43.963  1438  5124 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:126)
12-18 13:07:43.963  1438  5124 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:115)
12-18 13:07:43.963  1438  5124 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.continueLayout(WindowSurfacePlacer.java:97)
12-18 13:07:43.963  1438  5124 W WindowManager: 	at com.android.server.wm.ActivityTaskManagerService.continueWindowLayout(ActivityTaskManagerService.java:4659)
12-18 13:07:43.963  1438  5124 W WindowManager: 	at com.android.server.wm.ActivityTaskManagerService$LocalService.handleAppDied(ActivityTaskManagerService.java:6362)
12-18 13:07:43.963  1438  5124 W WindowManager: 	at com.android.server.am.ActivityManagerService.handleAppDiedLocked(ActivityManagerService.java:3396)
12-18 13:07:43.963  1438  5124 W WindowManager: 	at com.android.server.am.ActivityManagerService.appDiedLocked(ActivityManagerService.java:3500)
12-18 13:07:43.963  1438  5124 W WindowManager: 	at com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied(ActivityManagerService.java:1591)
12-18 13:07:43.963  1438  5124 W WindowManager: 	at android.os.IBinder$DeathRecipient.binderDied(IBinder.java:319)
12-18 13:07:43.963  1438  5124 W WindowManager: 	at android.os.BinderProxy.sendDeathNotice(BinderProxy.java:704)
12-18 13:07:43.964  1438  5124 W ProcessStats: Tracking association SourceState{fc0b87a com.android.phone/1001 BFgs #25011} whose proc state 4 is better than process ProcessState{fb274c0 android.process.acore/10033 pkg=com.android.providers.contacts (sub)} proc state 15 (2 skipped)
12-18 13:07:43.973  1438  2260 W WindowManager: Failed to deliver inset control state change to w=Window{489ae14 u0 com.github.tmo1.sms_ie/com.github.tmo1.sms_ie.MainActivity EXITING}
12-18 13:07:43.973  1438  2260 W WindowManager: android.os.DeadObjectException
12-18 13:07:43.973  1438  2260 W WindowManager: 	at android.os.BinderProxy.transactNative(Native Method)
12-18 13:07:43.973  1438  2260 W WindowManager: 	at android.os.BinderProxy.transact(BinderProxy.java:584)
12-18 13:07:43.973  1438  2260 W WindowManager: 	at android.view.IWindow$Stub$Proxy.insetsControlChanged(IWindow.java:479)
12-18 13:07:43.973  1438  2260 W WindowManager: 	at com.android.server.wm.WindowState.notifyInsetsControlChanged(WindowState.java:3818)
12-18 13:07:43.973  1438  2260 W WindowManager: 	at com.android.server.wm.InsetsStateController.lambda$notifyPendingInsetsControlChanged$3(InsetsStateController.java:369)
12-18 13:07:43.973  1438  2260 W WindowManager: 	at com.android.server.wm.InsetsStateController.$r8$lambda$8yykPRG1GyNq_J17QvL9d5xANMc(InsetsStateController.java:0)
12-18 13:07:43.973  1438  2260 W WindowManager: 	at com.android.server.wm.InsetsStateController$$ExternalSyntheticLambda2.run(R8$$SyntheticClass:0)
12-18 13:07:43.973  1438  2260 W WindowManager: 	at com.android.server.wm.WindowAnimator.executeAfterPrepareSurfacesRunnables(WindowAnimator.java:294)
12-18 13:07:43.973  1438  2260 W WindowManager: 	at com.android.server.wm.RootWindowContainer.performSurfacePlacementNoTrace(RootWindowContainer.java:811)
12-18 13:07:43.973  1438  2260 W WindowManager: 	at com.android.server.wm.RootWindowContainer.performSurfacePlacement(RootWindowContainer.java:756)
12-18 13:07:43.973  1438  2260 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop(WindowSurfacePlacer.java:177)
12-18 13:07:43.973  1438  2260 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:126)
12-18 13:07:43.973  1438  2260 W WindowManager: 	at com.android.server.wm.WindowManagerService.relayoutWindow(WindowManagerService.java:2386)
12-18 13:07:43.973  1438  2260 W WindowManager: 	at com.android.server.wm.Session.relayout(Session.java:254)
12-18 13:07:43.973  1438  2260 W WindowManager: 	at android.view.IWindowSession$Stub.onTransact(IWindowSession.java:701)
12-18 13:07:43.973  1438  2260 W WindowManager: 	at com.android.server.wm.Session.onTransact(Session.java:183)
12-18 13:07:43.973  1438  2260 W WindowManager: 	at android.os.Binder.execTransactInternal(Binder.java:1361)
12-18 13:07:43.973  1438  2260 W WindowManager: 	at android.os.Binder.execTransact(Binder.java:1302)
12-18 13:07:43.974  2654  2654 D BaseDepthController: setSurface:
12-18 13:07:43.974  2654  2654 D BaseDepthController: 	mWaitingOnSurfaceValidity: false
12-18 13:07:43.974  2654  2654 D BaseDepthController: 	mSurface: Surface(name=com.android.launcher3/com.android.launcher3.uioverrides.QuickstepLauncher)/@0xfaaacf1
12-18 13:07:43.975   767   767 W gralloc4: Unable to set buffer name VRI[QuickstepLauncher]#204(BLAST Consumer)204: File name too long
12-18 13:07:43.976   767   767 W gralloc4: Unable to set buffer name VRI[QuickstepLauncher]#204(BLAST Consumer)204: File name too long
12-18 13:07:43.977   767   767 W gralloc4: Unable to set buffer name VRI[QuickstepLauncher]#204(BLAST Consumer)204: File name too long
12-18 13:07:43.978   767   767 W gralloc4: Unable to set buffer name VRI[QuickstepLauncher]#204(BLAST Consumer)204: File name too long
12-18 13:07:43.978   767   767 W gralloc4: Unable to set buffer name VRI[QuickstepLauncher]#204(BLAST Consumer)204: File name too long
12-18 13:07:43.997  1438  1659 V WindowManager: Sent Transition #666 createdAt=12-18 13:07:43.900 via request=TransitionRequestInfo { type = 2, triggerTask = null, remoteTransition = null, displayChange = null, flags = 16 }
12-18 13:07:43.997  1438  1659 V WindowManager:     startWCT=WindowContainerTransaction { changes = {} hops = [] errorCallbackToken=null taskFragmentOrganizer=null }
12-18 13:07:43.997  1438  1659 V WindowManager:     info={id=666 t=CLOSE f=0x10 trk=1 r=[0@Point(0, 0)] c=[{WCT{RemoteToken{d1e5801 Task{4e4bd3b #1 type=home}}} m=TO_FRONT f=SHOW_WALLPAPER|MOVE_TO_TOP leash=Surface(name=Task=1)/@0xe875264 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0},{WCT{RemoteToken{c55f09b Task{4b86287 #86 type=standard A=10151:com.github.tmo1.sms_ie}}} m=CLOSE f=NONE leash=Surface(name=Task=86)/@0xe411b7f sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0},{null m=TO_FRONT f=IS_WALLPAPER leash=Surface(name=WallpaperWindowToken{fe34715 token=android.os.Binder@78ff8cc})/@0xac76d88 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0}]}
12-18 13:07:43.998  2149  2221 V WindowManagerShell: onTransitionReady android.os.BinderProxy@e4dc3c8: {id=666 t=CLOSE f=0x10 trk=1 r=[0@Point(0, 0)] c=[{WCT{android.window.IWindowContainerToken$Stub$Proxy@12b8212} m=TO_FRONT f=SHOW_WALLPAPER|MOVE_TO_TOP leash=Surface(name=Task=1)/@0xe17b386 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0},{WCT{android.window.IWindowContainerToken$Stub$Proxy@d140de3} m=CLOSE f=NONE leash=Surface(name=Task=86)/@0x86e7447 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0},{null m=TO_FRONT f=IS_WALLPAPER leash=Surface(name=WallpaperWindowToken{fe34715 token=android.os.Binder@78ff8cc})/@0x45f5474 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0}]}
12-18 13:07:43.998  2149  2221 V WindowManagerShell: Playing animation for (#666)android.os.BinderProxy@e4dc3c8@1
12-18 13:07:43.998  2149  2221 V WindowManagerShell:  try handler com.android.wm.shell.transition.DefaultMixedHandler@d0b480f
12-18 13:07:43.998  2149  2221 V WindowManagerShell:  try handler com.android.wm.shell.keyguard.KeyguardTransitionHandler@85c709c
12-18 13:07:43.998  2149  2221 V WindowManagerShell:  try handler com.android.wm.shell.pip.PipTransition@e53aaa5
12-18 13:07:43.998  2149  2221 V WindowManagerShell:  try handler com.android.wm.shell.activityembedding.ActivityEmbeddingController@83c1e7a
12-18 13:07:43.998  2149  2221 V WindowManagerShell:  try handler com.android.wm.shell.recents.RecentsTransitionHandler@f3e562b
12-18 13:07:43.998  2149  2221 V ShellRecents: RecentsTransitionHandler.startAnimation: no controller found
12-18 13:07:43.998  2149  2221 V WindowManagerShell:  try handler com.android.wm.shell.splitscreen.StageCoordinator@c0dfa88
12-18 13:07:43.998  2149  2221 V WindowManagerShell:  try handler com.android.wm.shell.transition.RemoteTransitionHandler@1794c21
12-18 13:07:43.998  2149  2221 V WindowManagerShell: Transition doesn't have explicit remote, search filters for match for {id=666 t=CLOSE f=0x10 trk=1 r=[0@Point(0, 0)] c=[{WCT{android.window.IWindowContainerToken$Stub$Proxy@12b8212} m=TO_FRONT f=SHOW_WALLPAPER|MOVE_TO_TOP leash=Surface(name=Task=1)/@0xe17b386 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0},{WCT{android.window.IWindowContainerToken$Stub$Proxy@d140de3} m=CLOSE f=NONE leash=Surface(name=Task=86)/@0x86e7447 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0},{null m=TO_FRONT f=IS_WALLPAPER leash=Surface(name=WallpaperWindowToken{fe34715 token=android.os.Binder@78ff8cc})/@0x45f5474 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0}]}
12-18 13:07:43.998  2149  2221 V WindowManagerShell:  Checking filter Pair{{types=[] flags=0x0] notFlags=0x100 checks=[{atype=home independent=true modes=[OPEN,TO_FRONT] flags=NONE mustBeTask=false order=TOP topActivity=ComponentInfo{com.android.launcher3/com.android.launcher3.uioverrides.QuickstepLauncher}},{atype=standard independent=true modes=[CLOSE,TO_BACK] flags=NONE mustBeTask=false order=ANY topActivity=null}]} RemoteTransition { remoteTransition = android.window.IRemoteTransition$Stub$Proxy@3da1e91, appThread = android.app.IApplicationThread$Stub$Proxy@e5561f6, debugName = QuickstepLaunchHome }}
12-18 13:07:43.998  2149  2221 D RemoteTransitionHandler: Found filterPair{{types=[] flags=0x0] notFlags=0x100 checks=[{atype=home independent=true modes=[OPEN,TO_FRONT] flags=NONE mustBeTask=false order=TOP topActivity=ComponentInfo{com.android.launcher3/com.android.launcher3.uioverrides.QuickstepLauncher}},{atype=standard independent=true modes=[CLOSE,TO_BACK] flags=NONE mustBeTask=false order=ANY topActivity=null}]} RemoteTransition { remoteTransition = android.window.IRemoteTransition$Stub$Proxy@3da1e91, appThread = android.app.IApplicationThread$Stub$Proxy@e5561f6, debugName = QuickstepLaunchHome }}
12-18 13:07:43.998  2149  2221 V WindowManagerShell:  Delegate animation for #666 to RemoteTransition { remoteTransition = android.window.IRemoteTransition$Stub$Proxy@3da1e91, appThread = android.app.IApplicationThread$Stub$Proxy@e5561f6, debugName = QuickstepLaunchHome }
12-18 13:07:44.000  2149  2221 V WindowManagerShell:  animated by com.android.wm.shell.transition.RemoteTransitionHandler@1794c21
12-18 13:07:44.007  2654  2654 D b/279059025: creating animation fromState: Background toState: Normal
12-18 13:07:44.008  2654  2654 D b/279059025: current animation cancelled
12-18 13:07:44.013  1438  5124 I ImeTracker: com.android.launcher3:945401a1: onRequestHide at ORIGIN_SERVER_HIDE_INPUT reason HIDE_UNSPECIFIED_WINDOW
12-18 13:07:44.014  1438  5124 I ImeTracker: com.android.launcher3:945401a1: onCancelled at PHASE_SERVER_SHOULD_HIDE
12-18 13:07:44.023  1438  1663 W WindowManager: Failed to deliver inset control state change to w=Window{489ae14 u0 com.github.tmo1.sms_ie/com.github.tmo1.sms_ie.MainActivity EXITING}
12-18 13:07:44.023  1438  1663 W WindowManager: android.os.DeadObjectException
12-18 13:07:44.023  1438  1663 W WindowManager: 	at android.os.BinderProxy.transactNative(Native Method)
12-18 13:07:44.023  1438  1663 W WindowManager: 	at android.os.BinderProxy.transact(BinderProxy.java:584)
12-18 13:07:44.023  1438  1663 W WindowManager: 	at android.view.IWindow$Stub$Proxy.insetsControlChanged(IWindow.java:479)
12-18 13:07:44.023  1438  1663 W WindowManager: 	at com.android.server.wm.WindowState.notifyInsetsControlChanged(WindowState.java:3818)
12-18 13:07:44.023  1438  1663 W WindowManager: 	at com.android.server.wm.InsetsStateController.lambda$notifyPendingInsetsControlChanged$3(InsetsStateController.java:369)
12-18 13:07:44.023  1438  1663 W WindowManager: 	at com.android.server.wm.InsetsStateController.$r8$lambda$8yykPRG1GyNq_J17QvL9d5xANMc(InsetsStateController.java:0)
12-18 13:07:44.023  1438  1663 W WindowManager: 	at com.android.server.wm.InsetsStateController$$ExternalSyntheticLambda2.run(R8$$SyntheticClass:0)
12-18 13:07:44.023  1438  1663 W WindowManager: 	at com.android.server.wm.WindowAnimator.executeAfterPrepareSurfacesRunnables(WindowAnimator.java:294)
12-18 13:07:44.023  1438  1663 W WindowManager: 	at com.android.server.wm.RootWindowContainer.performSurfacePlacementNoTrace(RootWindowContainer.java:811)
12-18 13:07:44.023  1438  1663 W WindowManager: 	at com.android.server.wm.RootWindowContainer.performSurfacePlacement(RootWindowContainer.java:756)
12-18 13:07:44.023  1438  1663 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop(WindowSurfacePlacer.java:177)
12-18 13:07:44.023  1438  1663 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:126)
12-18 13:07:44.023  1438  1663 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:115)
12-18 13:07:44.023  1438  1663 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer$Traverser.run(WindowSurfacePlacer.java:57)
12-18 13:07:44.023  1438  1663 W WindowManager: 	at android.os.Handler.handleCallback(Handler.java:958)
12-18 13:07:44.023  1438  1663 W WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-18 13:07:44.023  1438  1663 W WindowManager: 	at android.os.Looper.loopOnce(Looper.java:205)
12-18 13:07:44.023  1438  1663 W WindowManager: 	at android.os.Looper.loop(Looper.java:294)
12-18 13:07:44.023  1438  1663 W WindowManager: 	at android.os.HandlerThread.run(HandlerThread.java:67)
12-18 13:07:44.023  1438  1663 W WindowManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
12-18 13:07:44.115  1239  1283 I RFSD    : CNvFile::OnWriteDone
12-18 13:07:44.120  1239  1283 W RFSD    : [CsumCheckForFileAndForceCrash] /mnt/vendor/efs/nv_normal.bin checksum : verified
12-18 13:07:44.120  1239  1283 I RFSD    : [RfsService::Nv] CsumUpdate
12-18 13:07:44.120  1239  1283 I RFSD    : [RfsService::Nv] CsumCalc
12-18 13:07:44.144  1239  1283 I RFSD    : [RfsService::Nv] ProcessMessage : RFS_OP_STATUS
12-18 13:07:44.144  1135  1146 I modem_svc: Got userspace log indication
12-18 13:07:44.144  1239  1283 I RFSD    : [RfsService::Nv] ProcessMessage : RFS_STATUS_SUCCESS
12-18 13:07:44.144  1135  1146 D modem_svc: Modem: [CP2AP][RFSD] [NVTest] pal_RegStoreFlush fileName: ../../../LTESAE/LteL3/LteSae/SAEMM/Code/src/SAEMM_CommonProcedure.c, lineNum: 1862, nvId: 920, nvName: !SAEL3.KSIasme, EfsSyncCount: 371, actualCP2APCount:227
12-18 13:07:44.154   759   805 W VsyncModulator: setTransactionSchedule: Unexpected EarlyEnd
12-18 13:07:44.169  2149  2221 V WindowManagerShell: Transition animation finished (aborted=false), notifying core (#666)android.os.BinderProxy@e4dc3c8@1
12-18 13:07:44.172  1438  1659 V WindowManager: Finish Transition #666: created at 12-18 13:07:43.900 collect-started=0.087ms request-sent=0.298ms started=12.411ms ready=52.995ms sent=95.554ms finished=271.471ms
12-18 13:07:44.175  1438 19485 W WindowManager: Exception thrown during dispatchAppVisibility Window{489ae14 u0 com.github.tmo1.sms_ie/com.github.tmo1.sms_ie.MainActivity EXITING}
12-18 13:07:44.175  1438 19485 W WindowManager: android.os.DeadObjectException
12-18 13:07:44.175  1438 19485 W WindowManager: 	at android.os.BinderProxy.transactNative(Native Method)
12-18 13:07:44.175  1438 19485 W WindowManager: 	at android.os.BinderProxy.transact(BinderProxy.java:584)
12-18 13:07:44.175  1438 19485 W WindowManager: 	at android.view.IWindow$Stub$Proxy.dispatchAppVisibility(IWindow.java:546)
12-18 13:07:44.175  1438 19485 W WindowManager: 	at com.android.server.wm.WindowState.sendAppVisibilityToClients(WindowState.java:3287)
12-18 13:07:44.175  1438 19485 W WindowManager: 	at com.android.server.wm.WindowContainer.sendAppVisibilityToClients(WindowContainer.java:1299)
12-18 13:07:44.175  1438 19485 W WindowManager: 	at com.android.server.wm.WindowToken.setClientVisible(WindowToken.java:409)
12-18 13:07:44.175  1438 19485 W WindowManager: 	at com.android.server.wm.ActivityRecord.setClientVisible(ActivityRecord.java:6955)
12-18 13:07:44.175  1438 19485 W WindowManager: 	at com.android.server.wm.ActivityRecord.postApplyAnimation(ActivityRecord.java:5653)
12-18 13:07:44.175  1438 19485 W WindowManager: 	at com.android.server.wm.ActivityRecord.commitVisibility(ActivityRecord.java:5595)
12-18 13:07:44.175  1438 19485 W WindowManager: 	at com.android.server.wm.Transition.finishTransition(Transition.java:1198)
12-18 13:07:44.175  1438 19485 W WindowManager: 	at com.android.server.wm.TransitionController.finishTransition(TransitionController.java:886)
12-18 13:07:44.175  1438 19485 W WindowManager: 	at com.android.server.wm.WindowOrganizerController.finishTransition(WindowOrganizerController.java:419)
12-18 13:07:44.175  1438 19485 W WindowManager: 	at android.window.IWindowOrganizerController$Stub.onTransact(IWindowOrganizerController.java:280)
12-18 13:07:44.175  1438 19485 W WindowManager: 	at com.android.server.wm.WindowOrganizerController.onTransact(WindowOrganizerController.java:183)
12-18 13:07:44.175  1438 19485 W WindowManager: 	at android.os.Binder.execTransactInternal(Binder.java:1366)
12-18 13:07:44.175  1438 19485 W WindowManager: 	at android.os.Binder.execTransact(Binder.java:1302)
12-18 13:07:44.175  1438 19485 I Process : Sending signal. PID: 1440 SIG: 9
12-18 13:07:44.186  2149  2221 V WindowManagerShell: Track 1 became idle
12-18 13:07:44.186  2149  2221 V WindowManagerShell: All active transition animations finished
12-18 13:07:44.187  1438  1662 W ActivityManager: setHasOverlayUi called on unknown pid: 1440
12-18 13:07:44.193   759   759 E BpTransactionCompletedListener: Failed to transact (-32)
12-18 13:07:44.196 32621 32621 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@cabcc28
12-18 13:07:44.196  1438  2260 D CoreBackPreview: Window{2d68f5e u0 com.android.documentsui/com.android.documentsui.picker.PickActivity}: Setting back callback null
12-18 13:07:44.199  1438  2260 W InputManager-JNI: Input channel object '2d68f5e com.android.documentsui/com.android.documentsui.picker.PickActivity (client)' was disposed without first being removed with the input manager!
12-18 13:07:44.402  1438  1662 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{13772c6 u0 com.github.tmo1.sms_ie/.MainActivity t-1 f}}
12-18 13:07:44.443   892   896 I libperfmgr: Hint type not present in actions: ADPF_DISABLE_TA_BOOST
12-18 13:07:45.810   769  3032 D hwc-display: setActiveConfigWithConstraints:: PrimaryDisplay config(36) test(0)
12-18 13:07:45.811   769  3032 I hwc-display: [PrimaryDisplay] setActiveConfigWithConstraints: config(36)
```

**Comment by tmo1** [comment]
Thank you. I have reproduced the problem using your NDJSON and a random image file. I have a potential idea or two I'm going to look into.

**Comment by tmo1** [comment]
Hello,

The problem is the presence of the `sub_id`s in the MMS part metadata. This is probably related to #128, but in any event, I've implemented a fix by extending the behavior of the "Don't preserve Subscription IDs" setting to cover MMS part metadata. Please confirm that the fix (pushed to the repo - you can use the latest debug build) solves the problem.

**Comment by ma2thieu** [comment]
Hello thank you, I tried with the last debug [build](https://github.com/tmo1/sms-ie/actions/runs/7556990067) and the app doesn't crash anymore, I see the last screen telling me that the import went well but the images are still not imported and I see this error in the log : 
```
01-19 10:23:14.983  1445 12754 I ImeTracker: com.github.tmo1.sms_ie:2df8d72c: onRequestHide at ORIGIN_SERVER_HIDE_INPUT reason HIDE_UNSPECIFIED_WINDOW
01-19 10:23:14.983  1445 12754 I ImeTracker: com.github.tmo1.sms_ie:2df8d72c: onCancelled at PHASE_SERVER_SHOULD_HIDE
01-19 10:23:14.997   776 11274 W gralloc4: Unable to set buffer name bbq-adapter#242(BLAST Consumer)242: File name too long
01-19 10:23:15.001  2208  2284 V WindowManagerShell:  animated by com.android.wm.shell.transition.DefaultTransitionHandler@55de65a
01-19 10:23:15.005  4070 30191 D MediaProvider: Open with FUSE. FilePath: /storage/emulated/0/Share/messages-2023-12-09.zip. Uid: 10040. Media Capabilities Uid: 0. ShouldRedact: false. ShouldTranscode: false
01-19 10:23:15.065  7431  7587 D SMSIE   : Processing line #0
01-19 10:23:15.065  7431  7587 D SMSIE   : Message is SMS
01-19 10:23:15.092  1022  1022 I Zygote  : Process 5410 exited due to signal 9 (Killed)
01-19 10:23:15.108  2612  3165 V MmsProvider: accessRestricted=false
01-19 10:23:15.108  2612  3048 E DatabaseUtils: Writing exception to parcel
01-19 10:23:15.108  2612  3048 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading com.android.providers.telephony.SmsProvider uri content://sms/sent from pid=3253, uid=10157 requires android.permission.READ_SMS, or grantUriPermission()
01-19 10:23:15.108  2612  3048 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:1011)
01-19 10:23:15.108  2612  3048 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:813)
01-19 10:23:15.108  2612  3048 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:253)
01-19 10:23:15.108  2612  3048 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
01-19 10:23:15.108  2612  3048 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1387)
01-19 10:23:15.108  2612  3048 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1328)
01-19 10:23:15.109  7431  7587 D SMSIE   : SMS insert succeeded
01-19 10:23:15.109  3253  3491 D GmsCompat: java.lang.SecurityException: Permission Denial: reading com.android.providers.telephony.SmsProvider uri content://sms/sent from pid=3253, uid=10157 requires android.permission.READ_SMS, or grantUriPermission()
01-19 10:23:15.109  3253  3491 D GmsCompat: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
01-19 10:23:15.109  3253  3491 D GmsCompat: 	at android.os.Parcel.createException(Parcel.java:3050)
01-19 10:23:15.109  3253  3491 D GmsCompat: 	at android.os.Parcel.readException(Parcel.java:3026)
01-19 10:23:15.109  3253  3491 D GmsCompat: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
01-19 10:23:15.109  3253  3491 D GmsCompat: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
01-19 10:23:15.109  3253  3491 D GmsCompat: 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:495)
01-19 10:23:15.109  3253  3491 D GmsCompat: 	at android.content.ContentResolver.query(ContentResolver.java:1235)
01-19 10:23:15.109  3253  3491 D GmsCompat: 	at android.content.ContentResolver.query(ContentResolver.java:1167)
01-19 10:23:15.109  3253  3491 D GmsCompat: 	at android.content.ContentResolver.query(ContentResolver.java:1123)
01-19 10:23:15.109  3253  3491 D GmsCompat: 	at cvew.run(:com.google.android.gms@234212044@23.42.12 (190400-574052649):71)
01-19 10:23:15.109  3253  3491 D GmsCompat: 	at ajji.c(:com.google.android.gms@234212044@23.42.12 (190400-574052649):50)
01-19 10:23:15.109  3253  3491 D GmsCompat: 	at ajji.run(:com.google.android.gms@234212044@23.42.12 (190400-574052649):76)
01-19 10:23:15.109  3253  3491 D GmsCompat: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
01-19 10:23:15.109  3253  3491 D GmsCompat: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
01-19 10:23:15.109  3253  3491 D GmsCompat: 	at ajon.run(:com.google.android.gms@234212044@23.42.12 (190400-574052649):8)
01-19 10:23:15.109  3253  3491 D GmsCompat: 	at java.lang.Thread.run(Thread.java:1012)
01-19 10:23:15.111  7431  7587 D SMSIE   : Processing line #1
01-19 10:23:15.112  7431  7587 D SMSIE   : Message is MMS
01-19 10:23:15.134  2612  3048 V MmsProvider: accessRestricted=false
01-19 10:23:15.134  7431  7587 D SMSIE   : MMS insert succeeded
01-19 10:23:15.140  7431  7587 D SMSIE   : MMS address insert succeeded
01-19 10:23:15.142  7431  7587 D SMSIE   : MMS address insert succeeded
01-19 10:23:15.144  7431  7587 D SMSIE   : MMS address insert succeeded
01-19 10:23:15.146  7431  7587 D SMSIE   : MMS address insert succeeded
01-19 10:23:15.148  7431  7587 D SMSIE   : MMS address insert succeeded
01-19 10:23:15.150  7431  7587 D SMSIE   : MMS address insert succeeded
01-19 10:23:15.152  7431  7587 D SMSIE   : MMS part insert succeeded
01-19 10:23:15.155  7431  7587 D SMSIE   : MMS part insert succeeded
01-19 10:23:15.169  4070 30191 D MediaProvider: Open with FUSE. FilePath: /storage/emulated/0/Share/messages-2023-12-09.zip. Uid: 10040. Media Capabilities Uid: 0. ShouldRedact: false. ShouldTranscode: false
01-19 10:23:15.173  7431  7587 D SMSIE   : Writing part: data/PART_1701708600109_7233852881.jpg
01-19 10:23:15.177  2612  3165 V MmsProvider: accessRestricted=false
01-19 10:23:15.233  2208  2284 V WindowManagerShell: Transition animation finished (aborted=false), notifying core (#211)android.os.BinderProxy@3cfe267@0
01-19 10:23:15.237  1445  1669 V WindowManager: Finish Transition #211: created at 01-19 10:23:14.892 collect-started=0.172ms request-sent=0.318ms started=7.742ms ready=12.075ms sent=48.46ms finished=344.293ms
```

**Comment by tmo1** [comment]
I'm not sure what's going on here. The exception here seems to be caused by the SMS, not the MMS. Please make sure that you have granted the app READ_SMS permission, and please post the logs from import runs of just SMS and just MMS.

**Comment by ma2thieu** [comment]
Yes that's strange, I checked and the app does have the permission SMS=allow
I tried again with just 1 SMS, then 1 MMS and then with the same file as before (1 SMS + 1 MMS) and there is no crash, I get the "1 MMS imported" screen and no bug in the logs this time. But the images are still not there in the SMS app.
I tried with 2 different MMS with the same result.

This is the log for a file with 1 MMS with 1 jpeg.
```
01-23 18:20:56.804  1445  2259 I ImeTracker: com.github.tmo1.sms_ie:902a60b7: onRequestHide at ORIGIN_SERVER_HIDE_INPUT reason HIDE_UNSPECIFIED_WINDOW
01-23 18:20:56.804  1445  2259 I ImeTracker: com.github.tmo1.sms_ie:902a60b7: onCancelled at PHASE_SERVER_SHOULD_HIDE
01-23 18:20:56.807  4070 30285 D MediaProvider: Open with FUSE. FilePath: /storage/emulated/0/Share/mms2.zip. Uid: 10040. Media Capabilities Uid: 0. ShouldRedact: false. ShouldTranscode: false
01-23 18:20:56.816   776 23580 W gralloc4: Unable to set buffer name bbq-adapter#1807(BLAST Consumer)1807: File name too long
01-23 18:20:56.820  2208  2284 V WindowManagerShell:  animated by com.android.wm.shell.transition.DefaultTransitionHandler@55de65a
01-23 18:20:56.820 15151 15244 D SMSIE   : Processing line #0
01-23 18:20:56.824 15151 15244 D SMSIE   : Message is MMS
01-23 18:20:56.846 15151 15244 D SMSIE   : MMS insert succeeded
01-23 18:20:56.846  2612  3368 V MmsProvider: accessRestricted=false
01-23 18:20:56.852 15151 15244 D SMSIE   : MMS address insert succeeded
01-23 18:20:56.854 15151 15244 D SMSIE   : MMS address insert succeeded
01-23 18:20:56.856 15151 15244 D SMSIE   : MMS address insert succeeded
01-23 18:20:56.858 15151 15244 D SMSIE   : MMS address insert succeeded
01-23 18:20:56.861 15151 15244 D SMSIE   : MMS address insert succeeded
01-23 18:20:56.864 15151 15244 D SMSIE   : MMS address insert succeeded
01-23 18:20:56.867 15151 15244 D SMSIE   : MMS part insert succeeded
01-23 18:20:56.873 15151 15244 D SMSIE   : MMS part insert succeeded
01-23 18:20:56.877 15151 15244 D SMSIE   : MMS part insert succeeded
01-23 18:20:56.880 15151 15244 D SMSIE   : MMS part insert succeeded
01-23 18:20:56.882 15151 15244 D SMSIE   : MMS part insert succeeded
01-23 18:20:56.893  4070 30285 D MediaProvider: Open with FUSE. FilePath: /storage/emulated/0/Share/mms2.zip. Uid: 10040. Media Capabilities Uid: 0. ShouldRedact: false. ShouldTranscode: false
01-23 18:20:56.899 15151 15244 D SMSIE   : Writing part: data/PART_1676224415104_IMG_2475.jpg
01-23 18:20:56.905  2612  3368 V MmsProvider: accessRestricted=false
```

**Comment by tmo1** [comment]
Okay, I'm going to have to see whether I can reproduce the problem. Please post a minimal Zip file that demonstrates the problem - start with one of the actual files that you used, extract `messages.ndjson`, redact any sensitive information from it, and then create a new Zip with the redacted `messages.ndjson` and any arbitrary JPG renamed to the same name as the original one, making sure to retain the internal file structure of the Zip file. Try to import the new file, and assuming you see the same error, post the file here.

**Comment by ma2thieu** [comment]
Here is the minimal zip I used : 
[mms1.zip](https://github.com/tmo1/sms-ie/files/14036147/mms1.zip)

**Comment by tmo1** [comment]
> Here is the minimal zip I used :

Thank you. I imported your Zipfile, and the image imported correctly (it appears along with the message in the standard message app). Since I cannot reproduce your problem, and there's nothing unusual in the logs (yours or mine), I'm not sure what else I can do.

**Comment by tmo1** [comment]
> Hello, so probably something wrong with my phone then, maybe a permission problem ? I will give it another try.

I really don't know. It's certainly possible that there's a bug in the app - Android message handling and storage is complex and opaque, and there may be corner cases where things don't work. I'm sorry I can't help further at this point.

>  Do you know where are supposed to be stored the imported images ?

According to the exports I've seen, they're stored in `/data/user_de/0/com.android.providers.telephony/app_parts/`, but I don't know if that's universal.

**Comment by pushkin-** [comment]
just commenting to say that I'm also experiencing this:

> No entry for content://mms/part/17676
